import { PREFIXES } from 'prefixes'


const NAMESPACE = 'PLAYER_FORM'

export const FETCH_PLAYER_INFO_TRIGGER = `${ PREFIXES.TRIGGER }/${ NAMESPACE }:FETCH_PLAYER_INFO`
export const FETCH_PLAYER_INFO_REQUEST = `${ PREFIXES.REQUEST }/${ NAMESPACE }:FETCH_PLAYER_INFO`
export const FETCH_PLAYER_INFO_SUCCESS = `${ PREFIXES.SUCCESS }/${ NAMESPACE }:FETCH_PLAYER_INFO`
export const FETCH_PLAYER_INFO_FAILURE = `${ PREFIXES.FAILURE }/${ NAMESPACE }:FETCH_PLAYER_INFO`
export const FETCH_PLAYER_INFO_FULFILL = `${ PREFIXES.FULFILL }/${ NAMESPACE }:FETCH_PLAYER_INFO`

export const UPDATE_PLAYER_INFO_TRIGGER = `${ PREFIXES.TRIGGER }/${ NAMESPACE }:UPDATE_PLAYER_INFO`
export const UPDATE_PLAYER_INFO_REQUEST = `${ PREFIXES.REQUEST }/${ NAMESPACE }:UPDATE_PLAYER_INFO`
export const UPDATE_PLAYER_INFO_SUCCESS = `${ PREFIXES.SUCCESS }/${ NAMESPACE }:UPDATE_PLAYER_INFO`
export const UPDATE_PLAYER_INFO_FAILURE = `${ PREFIXES.FAILURE }/${ NAMESPACE }:UPDATE_PLAYER_INFO`
export const UPDATE_PLAYER_INFO_FULFILL = `${ PREFIXES.FULFILL }/${ NAMESPACE }:UPDATE_PLAYER_INFO`
